const question = [
  // {quest: "", img: false, answer: false},
  {quest: "Memory hierarchy", img: "memory_hierarchy", answer: false},
  {quest: "RVO", img: false, answer: "Return Value Optimization"},
  {quest: "section .txt", img: "section_txt", answer: false},
  {quest: "CLR", img: false, answer: "Common Language Runtime(общеязыковая исполняющая среда) C# Virtual Machine"},
  {quest: "Dalvik", img: false, answer: "..a Java Virtual Machine"},
  {quest: "section .data variables", img: "section_data_vars", answer: false},
  {quest: "rsp register", img: false, answer: "stack pointer"},
  {quest: "section .bss", img: "section_bss", answer: false},
  {quest: "Compilation(translation/build) Model", img: false, answer: "Compiled(C++, C, Go, Pascal), Interpreted(JS, Java, bash, Lua), hybrid(JS, Java, Python, C#)"},
  {quest: "movq (in assembler)", img: false, answer: "q -> quad word"},
  {quest: "section .data", img: "section_data", answer: false},
  {quest: "Compiling stages", img: false, answer: "1. lexical analysys<br>2. syntax analysys<br>3. semantic analysys<br>4. intermedian analysys<br>5. optimization<br>6. machine code generation<br>7. linking"},
  {quest: "Какие структуры есть в Ассемблере", img: "asm_struct", answer: false},
  {quest: "rip register", img: false, answer: "p -> PC(program counter) общий<br>eip(instruction pointer) специфический"},
  {quest: "section .bss const variables", img: "section_bss_const_vars", answer: false},
];
